postgres:
  host: localhost
  port: 5432
  database: campaign_analytics
  user: postgres
  password: ""  # Leave empty if no password, or add your password
  
  # JDBC settings for PySpark
  jdbc_url: jdbc:postgresql://localhost:5432/campaign_analytics
  driver: org.postgresql.Driver
  jar_path: lib/postgresql-42.6.0.jar
  
  # Schemas
  schemas:
    bronze: bronze
    silver: silver
    gold: gold
    analytics: analytics